// GENERATED by make_levelset.py -- do not edit; regenerate instead.
//
// The biventricular myocardium as a signed level set, phi < 0 inside. Same four
// ellipsoids as make_biventricular.py and biventricular.jou.
//
// Use this rather than a GridFunction loaded from file: it is exact at every
// quadrature point at any order, and it re-projects correctly onto a refined
// background mesh (OptimizeMeshWithAMRAroundZeroLevelSet calls
// ProjectCoefficient after each GeneralRefinement; a GridFunctionCoefficient
// bound to the old mesh indexes by element number and returns garbage).
//
// In pmesh-fitting.cpp, add a surf_ls_type case:
//     else if (surf_ls_type == 7) { ls_coeff = new FunctionCoefficient(biv::LevelSet); }
#ifndef BIV_LEVEL_SET_HPP
#define BIV_LEVEL_SET_HPP

#include "mfem.hpp"
#include <algorithm>
#include <cmath>

namespace biv
{

// a, b, c, cx, cy, cz  [mm]
static const double LV_ENDO[6] = {25, 25, 60, 0, 0, 68};
static const double LV_EPI[6]  = {33, 33, 68, 0, 0, 68};
static const double RV_ENDO[6] = {32, 25, 48, 20, 0, 70};
static const double RV_EPI[6]  = {38, 31, 55, 20, 0, 70};
static const double ZBASE      = 90;
static const double SIGN       = 1.0;   // -1 flips inside/outside

// Approximate signed distance to an ellipsoid (Quilez). Exact on the surface,
// second-order accurate nearby, which is all the fitting term needs: it drives
// nodes to phi = 0 and uses grad/Hessian only for the direction of that step.
inline double SdEllipsoid(const mfem::Vector &p, const double E[6])
{
   const double a = E[0], b = E[1], c = E[2];
   const double px = p(0) - E[3], py = p(1) - E[4], pz = p(2) - E[5];
   const double k0 = std::sqrt(px*px/(a*a) + py*py/(b*b) + pz*pz/(c*c));
   // 0/0 at the centre only; the limit there is finite and negative.
   if (k0 == 0.0) { return -std::min(a, std::min(b, c)); }
   const double k1 = std::sqrt(px*px/(a*a*a*a) + py*py/(b*b*b*b)
                               + pz*pz/(c*c*c*c));
   return k0 * (k0 - 1.0) / k1;
}

// myocardium = (LVepi - LVcav) U (RVepi - RVcav - LVepi), truncated at ZBASE.
// The RV cavity is carved by the LV epicardium, so the septum is LV wall.
inline double LevelSet(const mfem::Vector &p)
{
   const double lve = SdEllipsoid(p, LV_EPI);
   const double lvc = SdEllipsoid(p, LV_ENDO);
   const double rve = SdEllipsoid(p, RV_EPI);
   const double rvc = SdEllipsoid(p, RV_ENDO);

   const double lv_wall = std::max(lve, -lvc);
   const double rv_wall = std::max(std::max(rve, -rvc), -lve);
   const double myo     = std::min(lv_wall, rv_wall);

   // Base plane only. z >= 0 is not imposed: the LV epicardial apex is at
   // exactly z = 0, so that half-space is tangent and would only crease phi.
   return SIGN * std::max(myo, p(2) - ZBASE);
}

} // namespace biv

#endif // BIV_LEVEL_SET_HPP
